package JPS;
import static JPS.JPSNode.*;

public class JPSSearchLookupTable {

    public static int JPS_CARDINAL_COST = 2378;
    public static int JPS_DIAGONAL_COST = 3363;
    public final static int[] JPSDirCost = {JPS_CARDINAL_COST, JPS_DIAGONAL_COST, JPS_CARDINAL_COST, JPS_DIAGONAL_COST, JPS_CARDINAL_COST, JPS_DIAGONAL_COST, JPS_CARDINAL_COST, JPS_DIAGONAL_COST};

    public final static char[][] JPSSearchLookupTable = {
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {5, JPSDIR_DOWN, JPSDIR_DOWNLEFT, JPSDIR_LEFT, JPSDIR_UPLEFT, JPSDIR_UP},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {5, JPSDIR_DOWN, JPSDIR_DOWNLEFT, JPSDIR_LEFT, JPSDIR_UPLEFT, JPSDIR_UP},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {5, JPSDIR_RIGHT, JPSDIR_DOWNRIGHT, JPSDIR_DOWN, JPSDIR_DOWNLEFT, JPSDIR_LEFT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {4, JPSDIR_RIGHT, JPSDIR_DOWN, JPSDIR_DOWNLEFT, JPSDIR_LEFT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {4, JPSDIR_DOWN, JPSDIR_DOWNLEFT, JPSDIR_LEFT, JPSDIR_UP},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {4, JPSDIR_DOWN, JPSDIR_DOWNLEFT, JPSDIR_LEFT, JPSDIR_UP},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {5, JPSDIR_RIGHT, JPSDIR_DOWNRIGHT, JPSDIR_DOWN, JPSDIR_DOWNLEFT, JPSDIR_LEFT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {4, JPSDIR_RIGHT, JPSDIR_DOWN, JPSDIR_DOWNLEFT, JPSDIR_LEFT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {3, JPSDIR_LEFT, JPSDIR_DOWNLEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {0},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {0},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {5, JPSDIR_LEFT, JPSDIR_UPLEFT, JPSDIR_UP, JPSDIR_UPRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {5, JPSDIR_LEFT, JPSDIR_UPLEFT, JPSDIR_UP, JPSDIR_UPRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {4, JPSDIR_LEFT, JPSDIR_UPLEFT, JPSDIR_UP, JPSDIR_RIGHT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {4, JPSDIR_DOWN, JPSDIR_LEFT, JPSDIR_UPLEFT, JPSDIR_UP},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {4, JPSDIR_LEFT, JPSDIR_UPLEFT, JPSDIR_UP, JPSDIR_RIGHT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {4, JPSDIR_DOWN, JPSDIR_LEFT, JPSDIR_UPLEFT, JPSDIR_UP},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_UPLEFT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {5, JPSDIR_UP, JPSDIR_UPRIGHT, JPSDIR_RIGHT, JPSDIR_DOWNRIGHT, JPSDIR_DOWN},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {4, JPSDIR_UP, JPSDIR_UPRIGHT, JPSDIR_RIGHT, JPSDIR_DOWN},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {4, JPSDIR_LEFT, JPSDIR_UP, JPSDIR_UPRIGHT, JPSDIR_RIGHT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {4, JPSDIR_LEFT, JPSDIR_UP, JPSDIR_UPRIGHT, JPSDIR_RIGHT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {4, JPSDIR_RIGHT, JPSDIR_DOWNRIGHT, JPSDIR_DOWN, JPSDIR_LEFT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {4, JPSDIR_UP, JPSDIR_RIGHT, JPSDIR_DOWNRIGHT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {3, JPSDIR_UP, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {2, JPSDIR_UP, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {4, JPSDIR_RIGHT, JPSDIR_DOWNRIGHT, JPSDIR_DOWN, JPSDIR_LEFT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {3, JPSDIR_LEFT, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {2, JPSDIR_LEFT, JPSDIR_DOWN},
            {1, JPSDIR_LEFT},
            {0},
            {0},
            {0},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_LEFT},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {0},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {5, JPSDIR_UP, JPSDIR_UPRIGHT, JPSDIR_RIGHT, JPSDIR_DOWNRIGHT, JPSDIR_DOWN},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {4, JPSDIR_UP, JPSDIR_UPRIGHT, JPSDIR_RIGHT, JPSDIR_DOWN},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {3, JPSDIR_RIGHT, JPSDIR_UPRIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {0},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {4, JPSDIR_UP, JPSDIR_RIGHT, JPSDIR_DOWNRIGHT, JPSDIR_DOWN},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {2, JPSDIR_RIGHT, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {2, JPSDIR_DOWN, JPSDIR_UP},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {1, JPSDIR_UP},
            {0},
            {1, JPSDIR_DOWN},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {3, JPSDIR_DOWN, JPSDIR_DOWNRIGHT, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {0},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {2, JPSDIR_DOWN, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {1, JPSDIR_RIGHT},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {1, JPSDIR_DOWN},
            {1, JPSDIR_DOWN},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
            {0},
    };

}
