/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnitest_TestJNI */

#ifndef _Included_jnitest_TestJNI
#define _Included_jnitest_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnitest_TestJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnitest_TestJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     jnitest_TestJNI
 * Method:    arrayTest
 * Signature: ([Ljnitest/TestJNI/DataA;)V
 */
JNIEXPORT void JNICALL Java_jnitest_TestJNI_arrayTest
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
